from abc import ABC, abstractmethod
from typing import List, AsyncGenerator, Optional
from models import Message

class BaseProvider(ABC):
    @abstractmethod
    async def embed_text(self, text: str) -> List[float]:
        """Convert text into a vector embedding."""
        pass

    async def embed_query(self, text: str) -> List[float]:
        """Convert a search query into a vector embedding."""
        return await self.embed_text(text)

    @abstractmethod
    async def embed_texts(self, texts: List[str]) -> List[List[float]]:
        """Convert a list of texts into vector embeddings."""
        pass

    @abstractmethod
    async def chat_stream(
        self,
        messages: List[Message],
        model: str = None,
        temperature: float = 0.7,
        max_tokens: int = 2048
    ) -> AsyncGenerator[str, None]:
        """Stream a chat response from the LLM."""
        pass

    async def agent_stream(
        self,
        messages: list,
        tools: list,
        model: str = None,
        temperature: float = 0.5,
        max_tokens: int = 4096,
    ) -> AsyncGenerator[dict, None]:
        """
        Stream an agent response that may include tool calls.
        Yields dicts:
          {"type": "text", "content": "..."}
          {"type": "tool_request", "tool": "name", "args": {...}, "call_id": "..."}
        Default: falls back to plain chat_stream with no tool support.
        """
        import uuid
        msg_objects = [Message(role=m["role"], content=m.get("content") or "") for m in messages if m.get("role") != "tool"]
        full = ""
        async for chunk in self.chat_stream(msg_objects, model=model, temperature=temperature, max_tokens=max_tokens):
            full += chunk
            yield {"type": "text", "content": chunk}

    @abstractmethod
    def get_embedding_dimension(self) -> int:
        """Return the dimension of embeddings generated by this provider."""
        pass

    def get_collection_name(self) -> str:
        """Return the vector collection used by this provider."""
        provider_name = getattr(self, "provider_name", self.__class__.__name__.lower())
        safe_name = "".join(c if c.isalnum() else "_" for c in provider_name.lower())
        return f"notes_{safe_name}_{self.get_embedding_dimension()}"
