from abc import ABC, abstractmethod
from typing import List, AsyncGenerator
from models import Message

class BaseProvider(ABC):
    @abstractmethod
    async def embed_text(self, text: str) -> List[float]:
        """Convert text into a vector embedding."""
        pass

    async def embed_query(self, text: str) -> List[float]:
        """Convert a search query into a vector embedding."""
        return await self.embed_text(text)

    @abstractmethod
    async def embed_texts(self, texts: List[str]) -> List[List[float]]:
        """Convert a list of texts into vector embeddings."""
        pass

    @abstractmethod
    async def chat_stream(
        self,
        messages: List[Message],
        model: str = None,
        temperature: float = 0.7,
        max_tokens: int = 2048
    ) -> AsyncGenerator[str, None]:
        """Stream a chat response from the LLM."""
        pass
    
    @abstractmethod
    def get_embedding_dimension(self) -> int:
        """Return the dimension of embeddings generated by this provider."""
        pass

    def get_collection_name(self) -> str:
        """Return the vector collection used by this provider."""
        provider_name = getattr(self, "provider_name", self.__class__.__name__.lower())
        safe_name = "".join(c if c.isalnum() else "_" for c in provider_name.lower())
        return f"notes_{safe_name}_{self.get_embedding_dimension()}"
